site_name: IWEF

plugins:
  - mkdocstrings

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - python

nav:
  - IWEF: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md
