site_name: RiverText
site_description:  RiverText is a Python Library for Training and Evaluating Incremental Word Embeddings from Text Data Streams.
site_author: Gabriel Iturra
site_url: https://github.com/dccuchile/rivertext


plugins:
  - mkdocstrings
  - mkdocs-jupyter:
      execute: true
      ignore: ["./docs/examples/tweets.txt"]
      
repo_name: RiverText
repo_url: https://github.com/dccuchile/rivertext
edit_uri: https://github.com/dccuchile/rivertext

theme:
    name: material
    custom_dir: docs/overrides
    locale: en
    analytics: {gtag: 'G-274394082'}
    highlightjs: true
    hljs_languages:
        - yaml
        - python
    features:
      - navigation.tabs

# Copyright

copyright: Copyright &copy; 2023


nav:
  - Home: index.md
  - Introduction:
      - getting_started.md
      - About: introduction/about.md
  - API:
      - overview.md
      - utils:
          - data: api/data.md
          - rand: api/rand.md
          - vocab: api/vocab.md
      - models:
          - base: api/base.md
          - iword2vec_utils:
            - pytorch_nn: api/pytorch_nn.md
            - unigram_table: api/unigram_table.md
          - wcm: api/wcm.md
          - word2vec: api/w2v.md
      - evaluator: api/evaluator.md
  - Examples:
      - examples/textstreams.ipynb
      - examples/wcm.ipynb
  - Release: release.md
  - Benchmark: benchmark.md

extra:
  version: 0.0.1

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

extra_css:
  - stylesheets/extra.css
