site_name: RiverText

plugins:
  - mkdocstrings

repo_name: RiverText
repo_url: https://github.com/dccuchile/rivertext


theme:
    name: material
    locale: en
    analytics: {gtag: 'G-274394082'}
    highlightjs: true
    hljs_languages:
        - yaml
        - python
    features:
      - navigation.tabs

# Copyright
copyright: Copyright &copy; 2023


nav:
  - Introduction:
    - Welcome!: index.md
  - Introduction:
      - Installation: getting_started/about.md  
      - About: getting_started/about.md
  - User Guide: tutorials.md
  - API:
      - utils:
          - data: api/data.md
          - rand: api/rand.md
          - vocab: api/vocab.md
      - models:
          - base: api/base.md
          - iword2vec_utils:
            - pytorch_nn: api/pytorch_nn.md
            - unigram_table: api/unigram_table.md
          - wcm: api/wcm.md
          - word2vec: api/w2v.md
      - evaluator: api/evaluator.md
  - Contributing: reference.md
  - Overall Ranking: reference.md
