site_name: IWEF

plugins:
  - mkdocstrings

repo_name: IWEF
repo_url: https://github.com/giturra/iwef


theme:
    name: material
    locale: en
    analytics: {gtag: 'G-274394082'}
    highlightjs: true
    hljs_languages:
        - yaml
        - python


nav:
  - index.md
  - Getting Started:
      - About: getting_started/about.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md
